trigger:
  - main

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)/nuget'

steps:

# Install the required .NET SDK version
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.x'  # Replace with the .NET SDK version you need

# Install NuGet CLI
- task: NuGetToolInstaller@1

# Restore dependencies
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# Build the project
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Create the NuGet package
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    configuration: '$(buildConfiguration)'
    outputDir: '$(outputDir)'

# Push the package to Azure Artifacts
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(outputDir)/*.nupkg'
    publishVstsFeed: 'SuperRandom/SizeOf8'  # Replace with your feed path
    allowPackageConflicts: true
